#!/bin/sh
# shellcheck disable=SC3043,SC2034,SC1090

CLI_LOCAL_PREVIEWS_DIR="$CLI_CACHE_DIR/local-previews"
CLI_LOCAL_PREVIEWS_SCRIPTS_DIR="$CLI_LOCAL_PREVIEWS_DIR/scripts"
CLI_LOCAL_PREVIEWS_IMGS_DIR="$CLI_LOCAL_PREVIEWS_DIR/imgs"
mkdir -p "$CLI_LOCAL_PREVIEWS_SCRIPTS_DIR" "$CLI_LOCAL_PREVIEWS_IMGS_DIR"

_preview_local() {
  while IFS= read -r line; do
    if [ "$CONFIG_ENABLE_PREVIEW" = "true" ] && [ "$line" != "$TXT_MENU_EXIT" ]; then
      local hash
      local script_path
      local img_path
      local thumbnailer_input_file
      local base_dir
      local candidate_path
      local random_seek

      hash="$(_util_generate_hash "$line")"
      script_path="$CLI_LOCAL_PREVIEWS_SCRIPTS_DIR/$hash.sh"
      img_path="$CLI_LOCAL_PREVIEWS_IMGS_DIR/$hash.jpg"

      base_dir="$1"
      candidate_path="$CONFIG_DOWNLOAD_DIR/$line"
      [ -n "$base_dir" ] && candidate_path="$base_dir/$line"

      if [ -f "$candidate_path" ]; then
        thumbnailer_input_file="$candidate_path"
      else
        [ -n "$base_dir" ] && candidate_path="$base_dir"
        thumbnailer_input_file="$(find "$candidate_path" -type f 2>/dev/null | awk 'BEGIN{srand()} rand() * NR < 1 {line = $0} END {print line}')"
      fi

      if [ -n "$thumbnailer_input_file" ]; then
        random_seek=$(od -An -N2 -i /dev/urandom | awk '{print ($1 % 100) + 1}')
        ffmpegthumbnailer -i "$thumbnailer_input_file" -o "$img_path" -t "$random_seek" -s 0 -m >/dev/null 2>&1
      fi

      if [ "$CONFIG_LAUNCHER" = "fzf" ]; then
        printf "%s|%s\n" "$script_path" "$line"
      elif [ "$CONFIG_LAUNCHER" = "rofi" ]; then
        printf "%s\0icon\x1f%s\n" "$line" "$img_path"
      else
        echo "$line"
        return
      fi

      if [ "$CONFIG_LAUNCHER" = "fzf" ]; then
        cat <<EOF >"$script_path"
. "$CLI_PREVIEW_SCRIPTS_DIR/fzf-preview.sh"
[ -s "$img_path" ] && fzf_preview "$img_path" 2>/dev/null 
EOF
      fi
    else
      echo "$line"
    fi
  done
}

_menu_main() {
  [ "$CONFIG_ENABLE_PREVIEW" = "true" ] && __preview_fzf_create_shared_script

  if [ ! -d "$CONFIG_DOWNLOAD_DIR" ]; then
    ui_notify_warning "Downloads directory not found: $CONFIG_DOWNLOAD_DIR"
    _util_byebye
  fi

  while true; do
    local type
    local video

    type=$(
      printf "%s\n%s" "$(command ls "$CONFIG_DOWNLOAD_DIR" 2>/dev/null)" "$TXT_MENU_EXIT" |
        _preview_local |
        ui_launcher_with_preview "Select the type of file to play"
    )

    case "$type" in
    "$TXT_MENU_EXIT" | "") _util_byebye ;;
    esac

    video=$(
      printf "%s\n%s" "$(find "$CONFIG_DOWNLOAD_DIR/$type" -type f 2>/dev/null | sed "s|^$CONFIG_DOWNLOAD_DIR/$type/||")" "$TXT_MENU_BACK" |
        _preview_local "$CONFIG_DOWNLOAD_DIR/$type" |
        ui_launcher_with_preview "Select the video"
    )

    case "$video" in
    "$TXT_MENU_BACK" | "") continue ;;
    "$TXT_MENU_EXIT") _util_byebye ;;
    esac

    play "$CONFIG_DOWNLOAD_DIR/$type/$video"

    ui_confirm "Do you want to play another video?" || _util_byebye
  done
}
